server:
  port: 8088
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: Apigateway
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: http://localhost:8082/
        predicates:
        - Path=/customers/**
      - id: order-service
        uri: http://localhost:8089/
        predicates:
        - Path=/orders/**

 